### PR TITLE
Fix empty bomutils folder

### PR DESCRIPTION
**Pull request by kost**
Having empty bomutils folder does not allow having Empire as git submodule among other problems when git have empty dir.

### CODE REVIEW

**Comment by xorrior** [comment]
Thanks!

**Comment by killswitch-GUI** [comment]
This turns out to break the bomutils install because its not empty

**Comment by kost** [comment]
By the book: directory should be deleted completely and created in install.sh directory. I don't see any reason why it should be there any way. But would like to get some feedback from devs...

**Comment by xorrior** [comment]
So in the past the bomutils directory was created as apart of the install.sh. I should have added the folder to .gitignore so it didn't get sucked up in every PR. I don't mind making that change

**Pull request merged**
