### PR TITLE
Added wmi_updater module

### PR DESCRIPTION
**Pull request by tristandostaler**
This module is based on the module powershell persistence/elevated/wmi but instead of running a stager, it fetches a file on the web/network and executes it. The idea is you put a launcher.bat (for example) accessible over internet and the agent will fetch it and run it. It allows to drop the database, change completely the Empire version, recreate a launcher.bat, put it in the same place and you agent will come back online to the new server. You don't need to keep the same certificate and all.

As an example, I saw this comment for release 1.5:

WARNING: this release modifies part of the backend database schema, so do not apply this update if you have existing agents on your Empire server. You will need to run ./setup/reset.sh to reinitialize the database.

This wmi_updater module fixes this issue because now you only need to generate a new launcher.bat and put it in the same place and the agent will come back at the specified moment.

### CODE REVIEW

**Comment by rvrsh3ll** [comment]
Thanks for the PR! I am encountering this error when testing. 
(Empire: powershell/persistence/elevated/wmi_updater) > execute
[>] Module is not opsec safe, run? [y/N] y
[!] Exception: powershell_launcher() takes exactly 2 arguments (1 given)

**Comment by tristandostaler** [comment]
Hi,
Thanks for this reply.
I just runned it locally and it runned fine without any error. 
"WMI persistence established using launcher_fetcher WMI subscription daily trigger at ..."

Can you provide the details of the options you used?

**Comment by xorrior** [comment]
@tristandostaler I'll take a look at this soon and see if there is anything missing from the module. Thanks for PR!

**Comment by tristandostaler** [comment]
@xorrior Perfect! Don't hesitate to ask me any question!

**Comment by xorrior** [comment]
@tristandostaler This should work. You just need to modify your function call to include a custom launcher string like so https://github.com/EmpireProject/Empire/blob/master/lib/common/helpers.py#L190 . This was recently added. Thanks again.

**Comment by tristandostaler** [comment]
@xorrior that should do it?

Thanks for your help!

**Comment by tristandostaler** [comment]
@xorrior that should do it?

Thanks for you help!
PS: good idea for the custom launcher!

**Comment by xorrior** [comment]
@tristandostaler Thanks for updating. Stamp of approval.

**Pull request merged**
