### PR TITLE
Initial enhancement patch for 409

### PR DESCRIPTION
**Pull request by hightopfade**
Pushing an initial pass at [Issue 409](https://github.com/EmpireProject/Empire/issues/409) for searching a large list of agents

(Empire) > list agents

[*] Active agents:

  Name            Lang  Internal IP     Machine Name    Username            Process             Delay    Last Seen
  ---------       ----  -----------     ------------    ---------           -------             -----    --------------------
  AVSE9CWH        ps    192.168.1.24    WIN-6CAHIEP8DJD *WIN-6CAHIEP8DJD\Admpowershell/3752     5/0.0    2017-10-17 12:54:22
  7D1RS2UZ        ps    192.168.1.24    WIN-6CAHIEP8DJD *WIN-6CAHIEP8DJD\Admpowershell/384      5/0.0    2017-10-17 12:54:23
  B7H4DWAU        ps    192.168.1.24    WIN-6CAHIEP8DJD *WIN-6CAHIEP8DJD\Admpowershell/3920     5/0.0    2017-10-17 13:04:46
  SB9G5KPD        ps    192.168.1.24    WIN-6CAHIEP8DJD *WIN-6CAHIEP8DJD\Admpowershell/4036     5/0.0    2017-10-17 13:04:51

(Empire) > list agents stale

[*] Active agents:

  Name            Lang  Internal IP     Machine Name    Username            Process             Delay    Last Seen
  ---------       ----  -----------     ------------    ---------           -------             -----    --------------------
  AVSE9CWH        ps    192.168.1.24    WIN-6CAHIEP8DJD *WIN-6CAHIEP8DJD\Admpowershell/3752     5/0.0    2017-10-17 12:54:22
  7D1RS2UZ        ps    192.168.1.24    WIN-6CAHIEP8DJD *WIN-6CAHIEP8DJD\Admpowershell/384      5/0.0    2017-10-17 12:54:23
  B7H4DWAU        ps    192.168.1.24    WIN-6CAHIEP8DJD *WIN-6CAHIEP8DJD\Admpowershell/3920     5/0.0    2017-10-17 13:04:46
  SB9G5KPD        ps    192.168.1.24    WIN-6CAHIEP8DJD *WIN-6CAHIEP8DJD\Admpowershell/4036     5/0.0    2017-10-17 13:04:51

(Empire) > list agents help
[*] Help menu for searching agents
        --search        What column to search (name, language, internal_ip, hostname, username, process_name)
        --startswith    What does the value startwith?
        --contains      What does the value contain?

Example:
        list agents --search name --startswith ABC
        list agents --search hostname --contains ABC

(Empire) > list agents --search name --startswith 7

[*] Active agents:

  Name            Lang  Internal IP     Machine Name    Username            Process             Delay    Last Seen
  ---------       ----  -----------     ------------    ---------           -------             -----    --------------------
  7D1RS2UZ        ps    192.168.1.24    WIN-6CAHIEP8DJD *WIN-6CAHIEP8DJD\Admpowershell/384      5/0.0    2017-10-17 12:54:23

(Empire) > list agents --search name --startswith B7

[*] Active agents:

  Name            Lang  Internal IP     Machine Name    Username            Process             Delay    Last Seen
  ---------       ----  -----------     ------------    ---------           -------             -----    --------------------
  B7H4DWAU        ps    192.168.1.24    WIN-6CAHIEP8DJD *WIN-6CAHIEP8DJD\Admpowershell/3920     5/0.0    2017-10-17 13:04:46

(Empire) > list agents --search name --startswith A

[*] Active agents:

  Name            Lang  Internal IP     Machine Name    Username            Process             Delay    Last Seen
  ---------       ----  -----------     ------------    ---------           -------             -----    --------------------
  AVSE9CWH        ps    192.168.1.24    WIN-6CAHIEP8DJD *WIN-6CAHIEP8DJD\Admpowershell/3752     5/0.0    2017-10-17 12:54:22

(Empire) > list agents --search name --contains 7H4

[*] Active agents:

  Name            Lang  Internal IP     Machine Name    Username            Process             Delay    Last Seen
  ---------       ----  -----------     ------------    ---------           -------             -----    --------------------
  B7H4DWAU        ps    192.168.1.24    WIN-6CAHIEP8DJD *WIN-6CAHIEP8DJD\Admpowershell/3920     5/0.0    2017-10-17 13:04:46

(Empire) > list agents --search name --contains 9G5

[*] Active agents:

  Name            Lang  Internal IP     Machine Name    Username            Process             Delay    Last Seen
  ---------       ----  -----------     ------------    ---------           -------             -----    --------------------
  SB9G5KPD        ps    192.168.1.24    WIN-6CAHIEP8DJD *WIN-6CAHIEP8DJD\Admpowershell/4036     5/0.0    2017-10-17 13:04:51

### CODE REVIEW

**Comment by xorrior** [comment]
@hightopfade  This doesn't seem to be working for me. 
image

image

**Comment by hightopfade** [comment]
Can you send me full details of your env please? Like  what you’re branched
from, Python version etc etc etc

**Comment by xorrior** [comment]
Yup
3.16.0-4-amd64 #1 SMP Debian 3.16.39-1+deb8u2 (2017-03-07) x86_64 GNU/Linux
Python 2.7.9

**Comment by xorrior** [comment]
@hightopfade Even after a fresh install on my current setup. This still doesn't work. I'll probably need to step through with a debugger to figure it out.

**Comment by xorrior** [comment]
@hightopfade sorry man, tested again on a Kali image (2017-08-30) and it's still not working for me. I don't know what I'm doing wrong. I followed what is shown in your examples.

**Comment by hightopfade** [comment]
Not a problem, I’ll refactor

**Comment by xorrior** [comment]
@hightopfade please feel free to re-open this when you're ready.

**Comment by d2-d2** [comment]
@xorrior hey, I just tested it. After git pull I'm on version 2.4 now and when executing list agents help I'm getting:
```
(Empire) > list agents help
[!] Please enter the minute window for agent checkin.
````

**Comment by xorrior** [comment]
@d2-d2 ok I'll play with this a bit. @hightopfade time for round 2 haha.

**Comment by hightopfade** [comment]
I’ll start working on this ASAP, when life happens...

**Comment by xorrior** [comment]
@hightopfade I tried to tackle this again today. I tried a generator expression and a lambda function instead querying the database directly. Neither of which produced results.

**Pull request closed without merging**
