### PR TITLE
Modifications to agents.py, http.py. Updates to socks library for Python agents

### PR DESCRIPTION
**Pull request by klustic**
Updated SOCKS proxy for Python agent
> Matches new version of AlmondRocks (v1.0.0)
Breaks compatibility with previous versions of AlmondRocks

Fixed exceptions and suppressed extraneous output in agents.py and http.py

> When running background modules, when the agent reported in, a database lookup was performed for "task=0" for that agent, which did not exist in the database. This was causing an exception that was written to the terminal, so that every 5 seconds (or, beacon interval) the terminal I/O was being interleaved with an error message. The database lookup was part of unused code, so that block has been removed.

> Additionally, the agents checking in also report the following:
```
[*] Agent SIOB3GNU returned results.
[*] Valid results returned by 172.17.0.1
```
>Those messages do not provide useful information and again, cause interleaved I/O after each beacon. The messages have been suppressed by setting "print" to False for the dispatch events

### CODE REVIEW

**Comment by xorrior** [comment]
@klustic It seems like the module executes on the agent without any issues but when I try to use the arox server, a channel is created and then closed. I tried to use curl to test but the connection timed out. Not sure if I'm missing something. 

image

image

image

**Comment by klustic** [comment]
@xorrior I am able to replicate this issue when my proxychains config mistakenly is set to `socks4`. Please verify that your proxychains.conf file includes a `socks5` entry pointing to the AROX socks port:

**SOCKSv5**
```
root@76c20154200b:/# grep 1080 /etc/proxychains.conf 
socks5 	192.168.86.38 1080

root@76c20154200b:/# proxychains curl -H "Host: ipv4.icanhazip.com" 69.162.69.149
ProxyChains-3.1 (http://proxychains.sf.net)
|S-chain|-<>-192.168.86.38:1080-<><>-69.162.69.149:80-<><>-OK
<my ip address correctly returned>

root@76c20154200b:/# proxychains curl ipv4.icanhazip.com  
ProxyChains-3.1 (http://proxychains.sf.net)
|DNS-request| ipv4.icanhazip.com 
|S-chain|-<>-192.168.86.38:1080-<><>-4.2.2.2:53-<><>-OK
|DNS-response| ipv4.icanhazip.com is 69.162.69.149
|S-chain|-<>-192.168.86.38:1080-<><>-69.162.69.149:80-<><>-OK
<my ip address correctly returned>
```

**SERVER**

```
root@60d47bdb2569:/opt/arox# python arox.py -v server --cert ssl/cert.pem --key ssl/key.pem -s 0.0.0.0:1080 -t 0.0.0.0:4433
[2018-06-07 02:41:54]  WARNING SocksServer: Waiting for Tunnel connections on 0.0.0.0:4433
[2018-06-07 02:41:56]  WARNING SocksServer: Accepted Tunnel connection from 172.17.0.1:58194
[2018-06-07 02:41:56]     INFO SocksServer: Listening for SOCKSv5 clients on 0.0.0.0:1080
[2018-06-07 02:42:01]     INFO SocksServer: Created new channel: <Channel id=2005808529 remote_addr=None local_addr=172.17.0.1:34514>
[2018-06-07 02:42:01]     INFO SocksServer: Channel connected remotely: <Channel id=2005808529 remote_addr=69.162.69.149[69.162.69.149]:80 local_addr=172.17.0.1:34514>
[2018-06-07 02:42:01]     INFO Tunnel: Closed channel: <Channel id=2005808529 remote_addr=69.162.69.149[69.162.69.149]:80 local_addr=172.17.0.1:34514>
[2018-06-07 02:42:01]     INFO SocksServer: Closed a channel: <Channel id=2005808529 remote_addr=69.162.69.149[69.162.69.149]:80 local_addr=172.17.0.1:34514>
[2018-06-07 02:42:38]     INFO SocksServer: Created new channel: <Channel id=2005808530 remote_addr=None local_addr=172.17.0.1:34520>
[2018-06-07 02:42:38]     INFO SocksServer: Channel connected remotely: <Channel id=2005808530 remote_addr=4.2.2.2[4.2.2.2]:53 local_addr=172.17.0.1:34520>
[2018-06-07 02:42:38]     INFO Tunnel: Closed channel: <Channel id=2005808530 remote_addr=4.2.2.2[4.2.2.2]:53 local_addr=172.17.0.1:34520>
[2018-06-07 02:42:38]     INFO SocksServer: Created new channel: <Channel id=2005808531 remote_addr=None local_addr=172.17.0.1:34526>
[2018-06-07 02:42:38]     INFO SocksServer: Channel connected remotely: <Channel id=2005808531 remote_addr=69.162.69.149[69.162.69.149]:80 local_addr=172.17.0.1:34526>
[2018-06-07 02:42:38]     INFO Tunnel: Closed channel: <Channel id=2005808531 remote_addr=69.162.69.149[69.162.69.149]:80 local_addr=172.17.0.1:34526>
[2018-06-07 02:42:38]     INFO SocksServer: Closed a channel: <Channel id=2005808531 remote_addr=69.162.69.149[69.162.69.149]:80 local_addr=172.17.0.1:34526>
```

Please let me know if this isn't the issue, and if there's anything else you need from me

**Comment by xorrior** [comment]
@klustic I'll give that a try, thanks!

**Comment by xorrior** [comment]
@klustic This is awesome, thanks!

**Pull request merged**
