### PR TITLE
Added Get-AppLockerConfig

### PR DESCRIPTION
**Pull request by matterpreter**
This is a new situational awareness module that will check the AppLocker policy for a user-supplied executable or all executables in a filepath for a specified user.

### CODE REVIEW

**Comment by matterpreter** [comment]
Having a bit of an issue getting output from the script to come back to the agent and could use some help.

**Comment by winnie22** [comment]
Hi @matterpreter, you should replace Write-Host with Write-Output. With this change everything works for me:

`(Empire: powershell/situational_awareness/host/applockerstatus) > set Executable c:\windows\system32\calc.exe`
`(Empire: powershell/situational_awareness/host/applockerstatus) > execute`
`[*] Tasked 8NRZSV4X to run TASK_CMD_WAIT`
`[*] Agent 8NRZSV4X tasked with task ID 6`
`[*] Tasked agent 8NRZSV4X to run module powershell/situational_awareness/host/applockerstatus`
`(Empire: powershell/situational_awareness/host/applockerstatus) > [*] Agent 8NRZSV4X returned results.`
`[-] User does not exist. Exiting...`
`[*] Valid results returned by 192.168.1.10`
`(Empire: powershell/situational_awareness/host/applockerstatus) > set User winnie`
`(Empire: powershell/situational_awareness/host/applockerstatus) > execute`
`[*] Tasked 8NRZSV4X to run TASK_CMD_WAIT`
`[*] Agent 8NRZSV4X tasked with task ID 7`
`[*] Tasked agent 8NRZSV4X to run module powershell/situational_awareness/host/applockerstatus`
`(Empire: powershell/situational_awareness/host/applockerstatus) > [*] Agent 8NRZSV4X returned results.`
`[+] c:\windows\system32\calc.exe - ALLOWED for winnie!`
`[*] Valid results returned by 192.168.1.10`

**Comment by matterpreter** [comment]
Thanks @winnie22! Fixed in 5f62dde.

**Comment by xorrior** [comment]
@matterpreter Great work! Thanks

**Pull request merged**
