### PR TITLE
Generate bashrc to execute SR Automatic Via Drop File bashrc to File Home in file System 

### PR DESCRIPTION
**Pull request by jihadLkmaty218**
Can we discuss this With @xorrior And @424f424f  in Upload file this Generate ! in Empire 2.2  OR 3 !

### CODE REVIEW

**Comment by jihadLkmaty218** [comment]
now this Handler And Listener With @xorrior And @424f424f 😄
default project

**Comment by xorrior** [comment]
@jihadLkmaty218  can you provide a link to the PR in which this was added?

**Comment by jihadLkmaty218** [comment]
thank you @xorrior ❤️ 
https://github.com/jihadLkmaty218/Empire_2.2/blob/master/bashrc.py
And this : Generate File bashrc And execute Stager Automatic Via Drop File bashrc to File Home in file System 
Video
https://streamable.com/s80w1
-----------------------
----------------------- 
https://github.com/jihadLkmaty218/Empire_2.2/blob/master/Stager-Via-COM-Hijacking.py
Generate COM-Hijacking And execute File sct Via add Link raw file sct on gists or github 
Author i'am And @subTee 
Video
Soon Upload now 
----------------------------------

**Comment by jihadLkmaty218** [comment]
And I am happy to work with you thank you @xorrior After understanding the topic you can Tweet to  my @homjxi0e ::)

**Comment by jihadLkmaty218** [comment]
It can be uploaded within the latest version @xorrior

**Comment by xorrior** [comment]
@jihadLkmaty218 these are not PR's that are currently open in the project. I will not accept PR's that just generate launchers.

**Pull request closed without merging**
