### PR TITLE
NTSD code exec

### PR DESCRIPTION
**Pull request by hightopfade**
Pushing module for NTSD (NT Symbolic Debugger) code execution

### CODE REVIEW

**Comment by xorrior** [comment]
@hightopfade could you provide some screenshots demonstrating how to use this module? I've tried to execute the module in an Administrative context several times with no success.

**Comment by hightopfade** [comment]
working to troubleshoot some issues @xorrior identified when working with Win7 and Win10

**Comment by hightopfade** [comment]
Updated the invoke ntsd module

tested working on x86/x86_64 Win7, x86/x86_64 Win 8.1 and x86_64 Win 10

The conflicts are due to spacing issues... tabs v spaces...

Should probably create a "style" guide to ensure that everyone uses the same vimrc for tabs etc etc

**Comment by xorrior** [comment]
@hightopfade I'll take a look and try to get this merged tonight.

**Pull request merged**
