### PR TITLE
http Listener now evades Nessus plugin 99592

### PR DESCRIPTION
**Pull request by s0lst1c3**
About a month ago, Tenable released a Nessus plugin for identifying Empire http listeners. Since the plugin uses signature-based methods, I figured it wouldn’t be terribly difficult to evade. 

Tenable also released a blog post that describes how the plugin works and how the signature is constructed. It’s actually a pretty interesting read (link included below), but I’ll do my best to give you the _tl;dr_ version as well.

__Blog Post:__
[https://www.tenable.com/blog/identifying-empire-http-listeners](https://www.tenable.com/blog/identifying-empire-http-listeners)

__Nessus Plugin 99592:__
https://www.tenable.com/plugins/index.php?view=single&id=99592

## Summary of the Issue

Tenable's blog post states that while “a lot of work has gone into making agents difficult to find . . . less has been done to hide listeners.”

The blog post then demonstrates that the following attributes can be used to create a signature for the Empire http Listener:

- The 404 page uses hardcoded Werkzeug error message
- The 404 page is always 233 bytes
- Content for most 200 responses is a hardcoded default page
- Empire uses atypical cache-control headers
- Making a request to the _/_ route always results in a 404 response, while making a request to any other route results in a 200 response and hardcoded default page.

The last point is particularly interesting. There is no route defined for _/_. This means that anytime a user makes a request to _/_, he or she gets the hardcoded Werkzeug 404 response as shown in the console output below.

```
┌─[root@somberlain] - [~/Empire/lib/listeners] - [8550]
└─[$] curl -i http://10.10.10.100/
HTTP/1.0 404 NOT FOUND
Content-Type: text/html
Content-Length: 233
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
Expires: 0
Server: Microsoft-IIS/7.5
Date: Thu, 28 Dec 2017 05:06:07 GMT

<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 3.2 Final//EN">
<title>404 Not Found</title>
<h1>Not Found</h1>
<p>The requested URL was not found on the server.  If you entered the URL manually please check your spelling and try again.</p>
```

On the other hand, making a request to any other route (including /index.html) results in a 200 response containing a hardcoded default page.

```
┌─[root@somberlein] - [~/Empire/lib/listeners] - [8551]
└─[$] curl -i http://10.10.10.100/asdfasdfasdf                                                             [23:06:07]
HTTP/1.0 200 OK
Content-Type: text/html; charset=utf-8
Content-Length: 173
Cache-Control: no-cache, no-store, must-revalidate
Pragma: no-cache
Expires: 0
Server: Microsoft-IIS/7.5
Date: Thu, 28 Dec 2017 05:07:16 GMT

<html><body><h1>It works!</h1><p>This is the default web page for this server.</p><p>The web server software is running but no content has been added, yet.</p></body></html>
```

This behavior really makes the Empire http Listener stand out, since most production servers would do the opposite (_/_ and  /index.html would result in a default page, /* would result in a 404 error).

## Fixing the Problem

I was able to evade the signature based detections used by the Nessus plugin by adding the following enhancements to the http Listener:

- The http Listener behaves more like a “real” web server (which makes its signature more generic)
- The Content-Length for default and error pages is now randomly set on startup

To make the http Listener seem more like a generic web server, I first added a route for / and /index.html. When users make a request to either of these routes, they are presented with a 200 response containing the default index page for IIS 7.5.

empire-iis-index

However, when users attempt to access any route other than / or /index.html, they are now presented with a generic IIS 404 page.

empire-listener-404-page

This makes the http Listener behave identically to a generic IIS server, and eliminates easily identifiable hardcoded content (such as the Werkzeug 404 text).

To make it difficult to fingerprint the http Listener based on Content-Length, we simply append a whitespace buffer to the end of the index and 404 pages. The length of this whitespace buffer is randomly generated on startup but consistent across all requests.

I decided not to do anything about the cache-control headers, since cache-control headers vary enough across websites to make doing so unnecessary.

## Results

Aside from running basic unit tests on my code, I also made sure that the enhancements do an adequate job of evading the Nessus plugin. The results are shown below.

In the following screenshot, we perform a Nessus scan using plugin 99592 against a host running an Empire http Listener. As you can see, the plugin detects the http Listener.

empire-nessus-before

Next, we perform the same Nessus scan, but this time against a host running the enhanced Empire http Listener. Notice how the enhancements allow the Listener to successfully avoid detection. 

nessus-plugin-after

### CODE REVIEW

**Comment by xorrior** [comment]
@s0lst1c3 This is dope! Thanks for the help

**Comment by xorrior** [comment]
@s0lst1c3 I only had to make one change for a screw_up from another commit. Other than that, this is really cool. I will definitely implement this for the http_com listener as well.

**Comment by s0lst1c3** [comment]
Word, glad you liked it.

**Comment by s0lst1c3** [comment]
Also, also I'm down for implementing this for the http_com listener as well if you haven't already started that yet. Just let me know.

**Comment by xorrior** [comment]
Oh yea, definitely. I would really appreciate that @s0lst1c3

**Pull request merged**
