### PR TITLE
Fixed hardcoded certPath issue

### PR DESCRIPTION
**Pull request by ring0lab**
Fixed issue with hardcoded certPath for http listener.

### CODE REVIEW

**Comment by dchrastil** [comment]
Can you explain what the issue was? The cert path wasn't hard coded, just the names of the certs which are created upon install.

**Comment by ring0lab** [comment]
The names are hardcoded, which makes it impossible to assign CertPath = myownCert.pem for the HTTP listener. For an example when assigning CertPath = /myPath/Path/myDomain.pem, based on the current code. It would turn out like: context.load_cert_chain("**/myPath/Path/myDomain.pem/empire-chain.pem**" % (certPath), "**/myPath/Path/myDomain.pem/empire-priv.key**"  % (certPath)). I hope this makes sense.

**Comment by dchrastil** [comment]
I see what you are saying. As of now, the cert names are hard coded intentionally to support the self signed certs that are created on install, and the seperation of the pem and the priv key is required for domain fronting and certain SSL certificates. I think we need a more elegant solution to handle all situations.

Have you tried just overwriting the empire-chain.pem with your certificate and then pull out your priv key and save it as the empire-priv.key file? This should work in your scenario.

**Comment by ring0lab** [comment]
I haven't tried that method but I think that should solve the current issue.

**Comment by xorrior** [comment]
@ring0lab I think renaming the pem and key file in a custom path isn't too much to ask. If this becomes frequently requested change, then we can modify the listener options.

**Pull request closed without merging**
