### PR TITLE
Small tweaks and fixes to make the installer work on macOS

### PR DESCRIPTION
**Pull request by FreedomCoder**
**Empire Version** current master version 2.0
**OS Version** macOS Sierra 10.12.6
**Description**
- small edit on lib/common/helpers.py 
- added macOS detection and installation of requirements. 
- moved python requirements to requirements.txt file for easy of updating.

### CODE REVIEW

**Comment by rvrsh3ll** [comment]
Thanks! Will test. Please re-PR to dev branch.

**Comment by FreedomCoder** [comment]
👍

**Comment by rvrsh3ll** [comment]
Thanks!

**Comment by FreedomCoder** [comment]
Done. https://github.com/EmpireProject/Empire/pull/642

**Pull request closed without merging**
