### PR TITLE
Bugfix utf8 packet length

### PR DESCRIPTION
**Pull request by winnie22**
Hi, during my unicode bug hunting hell #542 :) I found error in data length counting. This issue affect at least linux agents. Without this fix part of the command remains in remainingData part of the packet and its not correctly executed.

### CODE REVIEW

**Comment by winnie22** [comment]
And it looks that this fix even windows agents. I can do cd now!
`(Empire: 8KA96UEN) > cd řěšč`
`[*] Tasked 8KA96UEN to run TASK_SHELL`
`[*] Agent 8KA96UEN tasked with task ID 15`
`(Empire: 8KA96UEN) > [*] Agent 8KA96UEN returned results.`
`Path                        `
`----                        `
`C:\Users\winnie\Desktop\řěšč`
`[*] Valid results returned by 172.16.83.14`

Only getting error in mkdir command:
`error running command: A positional parameter cannot be found that accepts argument 'Owner;Expression={ (Get-Acl mkdir.FullName).Owner }},lastwritetime,length,name'.`

**Comment by winnie22** [comment]
Last commit fix this issue.

**Comment by winnie22** [comment]
Hi @xorrior, I just realized that the same error is in 3.0 branch (https://github.com/EmpireProject/Empire/blob/3.0-Beta/lib/common/packets.py#L167). Will you fix it there or should I create PR for this branch too?

**Comment by xorrior** [comment]
@winnie22 I'll handing merging it with that branch. Thanks

**Comment by xorrior** [comment]
@winnie22 Thanks!

**Pull request merged**
