### PR TITLE
Add Wlrmdr.exe Popup module (Licensing Balloons)

### PR DESCRIPTION
**Pull request by benichmt1**
Along the same lines as trollsploit/message, this module is designed to pop up a licensing balloon in the taskbar.

Tested on:
Windows 8.1 x64
Windows 10 x64

wlrmdr

### CODE REVIEW

**Comment by killswitch-GUI** [comment]
@benichmt1 any chance you could set this up for beta_2.0? The module layout changed a bit.

**Comment by benichmt1** [comment]
Sure, I will give it a look this weekend. I'm assuming all new PRs should go to the beta_2.0 branch now?

**Comment by killswitch-GUI** [comment]
@benichmt1 yea thats defiantly ideal, otherwise this may not be ported over in the big release.

**Comment by xorrior** [comment]
Tested your 2.0_beta implementation. Looked at the code and looks good. Thanks

**Pull request merged**
