### PR TITLE
Added Custom Cookie Name and Random on HTTP Listeners

### PR DESCRIPTION
**Pull request by infosecn1nja**

### CODE REVIEW

**Comment by infosecn1nja** [comment]
@xorrior i am  currently developing custom cookie in the DefaultProfile and I will update on this PR as well.

```
#
# Amazon browsing traffic profile
# 
DefaultProfile
"/s/ref=nb_sb_noss_1/167-3294888-0262949/field-keywords=book,/N4215/adj/amzn.us.sr.aps|Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko|host:www.amazon.com|accept:*/*|Cookie:s_fid=6780A3DD5E29F2EC-3176EB904A03B94D; s_dslv=1521377892807; s_vn=1552913892809%26vn%3D1; s_nr=1521377892810-New; regStatus=pre-register; session-id=137-9165232-6583319; session-id-time=2082787201l; x-wl-uid=1cXuwDqZBSHyEJtXazV0frv/F0qSIDzLKTHxpM97LNZMPnxwuvm5VB7BgVtWYzUS8wS5Lq4pScL8=; ubid-main=133-6157397-7923333; session-token=8p/kzk/2QZxXjDP9iE+8kvJuob028ECSsc/3XWkgiLAQ/IwRyay56ckqEBRleoVIaDphKY96QyGTFjavra5RwWRa8xa3kgKEUh6zl5zzoxSSh3beXDE8vb1yZXMfVYgkrbSxBBdidwLyeT4M++Clfz5mBkw1Cnvz4yysfiAUAxb2HCixVUV6HDzqIk/OGhHNCp2DZBZHhL9HKJxUOrvhuChyIi6LaypnVOV2Fw+Uant1pkVe6tLpYpdBiFDIjFXI; skin=noskin; csm-hit=tbs-JCHJ9G7FNTNV72N0WW8V"

Headers
"Server:Server|x-amz-id-1:THKUYEZKCKPGY5T42PZT|x-amz-id-2:a21yZ2xrNDNtdGRsa212bGV3YW85amZuZW9ydG5rZmRuZ2tmZGl4aHRvNDVpbgo=|X-Frame-Options:SAMEORIGIN|Content-Encoding:gzip|x-ua-compatible: IE=edge"
```

image

**Comment by xorrior** [comment]
@infosecn1nja Is this PR ready to test?

**Comment by infosecn1nja** [comment]
Yes sure for this PR ready to test

**Comment by xorrior** [comment]
@infosecn1nja When trying to spawn or inject a new agent, it fails to stage and the routing packet is seemingly ignored. The new agent will stage once I exit and restart empire.

image

image

**Comment by infosecn1nja** [comment]
Hello @xorrior please try again, now I have fixed these issue.

Output spawn agent :
image


Output if restart empire :
image

Thank you

**Comment by infosecn1nja** [comment]
@xorrior i have make sure that now ready to PR, I have fixed all issues. Thanks

**Pull request merged**
