### PR TITLE
Add REST endpoint to allow adding creds to DB via POST request

### LINKED ISSUE #764: REST API for manually adding creds
## Empire Version
version 2.1 (latest)

#39 references this but in API docs there is only option to view all creds (https://github.com/EmpireProject/Empire/wiki/RESTful-API#credentials)

### PR DESCRIPTION
**Pull request by DakotaNelson**
Drawbacks right now:
- no validation beyond all fields being present and the `credtype` being either "hash" or "plaintext"
- creds are added to DB one at a time, which is slow for large batches

Not sure what the best way is to update the wiki; let me know and I'll go ahead and do that too.

This PR closes #764.

### CODE REVIEW

**Comment by xorrior** [comment]
@DakotaNelson can you provide me with an example of a request? I haven't been able to get it working with this format 
image

**Comment by DakotaNelson** [comment]
Pretty sure it's the square brackets:

```
{
	"credentials": [{
		"credtype":"plaintext",
		"domain":"domain2",
		"username":"username2",
		"password":"password2",
		"host":"host"
	},
	{
		"credtype":"plaintext",
		"domain":"domain3",
		"username":"username3",
		"password":"password3",
		"host":"host"
	}]
}
```

Should I put a better error message in there for "hey there should be a list and we found an object"?

**Comment by xorrior** [comment]
Ah thanks, i always appreciate verbose error output. I test this out again and merge if everything works.

**Comment by DakotaNelson** [comment]
Updated. I've also exported the Postman collection I used for testing: https://gist.github.com/DakotaNelson/189bb1b9fe2ff1c74f2f8da6522a3f47

**Comment by DakotaNelson** [comment]
Happy to help!

**Pull request merged**
