### PR TITLE
Hide true host name when using domain fronting

### PR DESCRIPTION
**Pull request by clr2of8**
Kudos to @malcomvetter for suggesting the solution implemented here.

Currently, when adding a host header via the .Net framework, as is done in the PowerShell multi/launcher,  the host name gets added to two places:

1) The HTTP header
2) The Server Name Indication (SNI) extension of the TLS client hello

The SNI is always sent in cleartext, giving away the true hostname that you are using behind your domain front. This code change simply adds a request to the root of the domain front before adding the host header, allowing the TLS connection to complete. Subsequent requests reuse this pre-established TLS connection. Therefore, adding the host name header at his point results in the value only being added to the HTTP header and not showing up in the client hello.

### CODE REVIEW

**Comment by malcomvetter** [comment]
Neat little trick!

**Comment by rvrsh3ll** [comment]
Good find!

**Comment by sjosz** [comment]
I'm using the latest version of PowerShell Empire (and I even checked if the code you wrote was in http.py), but the true destination is still revealed in the SNI, these are the steps I took:

listeners
uselistener http
set Name DomainFrontingHTTPS
set CertPath /home/empire/Empire/data/
set Host https://a0.awsstatic.com:443
set DefaultProfile /admin/get.php,/news.php,/login/process.php|Mozilla/5.0 (Windows NT 6.1; WOW64; Trident/7.0; rv:11.0) like Gecko|Host: ************.cloudfront.net
set Port 443
execute

2018-05-13 18_29_59-clipboard

 Does perhaps somebody have an idea on how to fix this? Maybe I'm doing something wrong here.

**Comment by clr2of8** [comment]
@sjosz where you using a python launcher in this case or a powershell launcher?

**Comment by sjosz** [comment]
PowerShell, I havent tested the Python launcher though.

**Pull request merged**
