### PR TITLE
 TLS version too low fix

### PR DESCRIPTION
**Pull request by byt3bl33d3r**
Got it right this time, re-submission of #712.

Cheers

### CODE REVIEW

**Comment by xorrior** [comment]
Thanks! I forgot that this change was need to finally fix #369

**Comment by nem0n** [comment]
Hi, there I am having the same issue with TLS version problem with Kali, what I wonder if the problem is the way to fix? because I saw that this issue was submitted 25 days ago.

**Comment by xorrior** [comment]
@nem0n What problem specifically? You can always change the TLS version back to TLS any or TLSv1.

**Comment by nem0n** [comment]
Oh sorry that's my fault I taught there was a some another problem rather
than version of TLS , i made the configuration now its working perfectly,
thank you

2017-10-18 6:41 GMT+03:00 Chris Ross <notifications@github.com>:

**Pull request merged**
