### PR TITLE
Docker support

### PR DESCRIPTION
**Pull request by frohoff**
Documentation available in [docker/README.md](https://github.com/frohoff/Empire/blob/docker/docker/README.md).

This iteration doesn't persist the database or cert outside of the container, but if the `empire.db` and `empire.pem` files could be moved into their own subdirectory it would allow them to be volume mounted separately from the rest of the files in `data` and persist outside of the container.

### CODE REVIEW

**Comment by xorrior** [comment]
I don't have much experience with docker. I'll test this as soon as I can.

**Comment by xorrior** [comment]
@frohoff I tested this and it seems to work well. 2 Things:
1. As you mentioned, the empire.db file does not persist. This is a bit of roadblock. Feel free to make changes to the folder structure in your PR. 
2. Since docker creates it's own network, maybe include some documentation or link on how to setup port forwarding?

Thanks again. Feel free to re-open this whenever you're ready.

**Comment by frohoff** [comment]
1. I'll take a look at making the required changes to the folder structure if this feature seems worthwhile and it doesn't seem like the change would be too invasive.
2. There's some docs in the ["Use port forward(s) for listeners"](https://github.com/frohoff/Empire/blob/docker/docker/README.md#use-port-forwards-for-listeners) section of the docker README in the PR that discusses this, as well the sample [`docker-compose.override.yml`](https://github.com/frohoff/Empire/blob/docker/docker/docker-compose.override.yml) with port forwarding commented out. I can elaborate on this if it doesn't seem sufficient.

Thanks.

**Comment by xorrior** [comment]
@frohoff I want to open this back up. I'll see if I can figure out how to get this working.

**Comment by xorrior** [comment]
Just adding links for future reference:
https://docs.oracle.com/cd/E37670_01/E75728/html/section_ffp_yt4_gp.html
https://docs.oracle.com/cd/E37670_01/E75728/html/section_vtr_p2z_fp.html

@frohoff During testing, how did you configure networking so that agents could communicate with listeners inside of the Docker network? That is the largest hurdle with this.

**Comment by frohoff** [comment]
I have a local version of this that is rebased against the most recent code I can push up soon if that helps.

Regarding networking, there's a couple options [as noted by the readme](https://github.com/frohoff/Empire/blob/docker/docker/README.md#a-note-about-networking):

### Forward a port
`docker-compose.override.yml`:
```yaml
version: "3"
services:
  empire:
    ports: ["80","443"]
```

### Run in `host` networking mode 
(doesn't currently work on docker for mac)
`docker-compose.override.yml`:
```yaml
version: "3"
services:
  empire:
    network_mode: host
```

If the container is already running, these changes can be applied by re-running `docker-compose up -d` to restart and reconfigure the running container.

**Comment by xorrior** [comment]
@frohoff I like the host networking option. We don't officially support OSX ;)

**Comment by frohoff** [comment]
Ok, I can make that the default in the `docker-compose.yml` and then people can override it in a `docker-compose.override.yml` if they need to.

**Comment by frohoff** [comment]
Also, are PRs still supposed to be based on the `dev` branch?

**Comment by frohoff** [comment]
Updated default `docker-compose.yml` file to use host network mode, updated readme, and rebased against latest dev branch.

**Comment by xorrior** [comment]
#848 has resolved this. This PR is no longer needed. Thanks @frohoff

**Pull request closed without merging**
