### PR TITLE
Update install.sh

### PR DESCRIPTION
**Pull request by whoot**
Added download link to powershell and updated libssl

### CODE REVIEW

**Comment by xorrior** [comment]
@SadProcessor This installs the the official release instead of the release candidate. Is there any reason why you went with that version instead of the official release?

**Comment by whoot** [comment]
Hey, 
uhm I just choosed the latest release, which was released 5 days ago.
However, if you want to install RC2, which was released on 14. Dec 2017, I can change it back.

The whole reason why I made this pull request was, because powershell isnt downloaded at all and the installation will fail.

**Comment by xorrior** [comment]
@whoot Understood. We can keep the official release.

**Comment by SadProcessor** [comment]
Think rc2 was latest at time of PR. since it's now GA, let's go for GA!!
I was using direct download in PR but maybe better to use apt-key method to avoid any version issues.
https://github.com/PowerShell/PowerShell/blob/master/docs/installation/linux.md#debian-9

**Pull request merged**
