### PR TITLE
Swap out PyCrypto for Cryptography

### PR DESCRIPTION
**Pull request by elitest**
This PR addresses the request made in #707.  I chose to use [cryptography](https://github.com/pyca/cryptography) for the crypto library as it is very mature(as python goes) and under heavy development and it is very likely to be installed already.  The only place that cryptography is actually used is in ```encryption.py```.  The use of ```random```(previously used by pycrypto's random function) is replaced by ```os.urandom```, in the places where keys or IVs are being generated(this is is cryptography's preferred solution to generating pseudo-random key material), in some cases I have swapped out PyCrypto's random function for python's standard library random.  This second use of random do not relate to direct use within crypto.

Testing:
I manually walked through the old AES functions and new AES functions in the interpreter while I was debugging things.  I also set up a new instance of Empire and spawned a listener and agent that successfully connected back.  I still would recommend testing these changes in dev for a decent bit!
 
There is one more reference to PyCrypto in the code, but that appeared to be related to something client side.

### CODE REVIEW

**Comment by xorrior** [comment]
@elitest What is the lowest version of Python that cryptography supports?

**Comment by elitest** [comment]
That is a great question.  According to PyPi and their GitHub page: "It supports Python 2.6-2.7, Python 3.4+, and PyPy 5.3+".  The fact that they are still supporting 2.6 I think is pretty impressive.  Based on my involvement in the project I think it will probably support 2.7 for a while, until Apple moves to python 3 in OS X.

**Comment by elitest** [comment]
So I have been thinking about this one.  It should be possible to actually remove the cryptography requirement if we pulled in something like [pyaes](https://github.com/ricmoo/pyaes) into lib/common/encryption.py.  Realistically, either PyCryptodome or Cryptography are heavier than the needs of the project unless we see the crypto needs of the project increasing.  Either way let me know if you need anything else.

**Comment by xorrior** [comment]
@elitest with the docker build now, I don't know if we'll really need to implement this.

**Pull request merged**
