### PR TITLE
Module new in Empire Create spasm on host machine

### PR DESCRIPTION
**Pull request by jihadLkmaty218**
Create spasm and consumption in memory and anxiety
— — — — — — — — — — — —
Create spasm and consumption in memory and anxiety by InfDefaultInstall.exe ok What is the InfDefaultInstall.exe ?
InfDefaultInstall.exe is a type of EXE file associated with Windows 10 Home Premium developed by Microsoft for the Windows Operating System. The latest known version of InfDefaultInstall.exe is 1.0.0.0, which was produced for Windows. This EXE file carries a popularity rating of 1 stars and a security rating of “UNKNOWN”.
Memory is consumed by running Thousands of them The reason for such an opening is to execute a command directly on Powershell
There are a lot of mistakes that exist on them::) 
“InfDefaultInstall.exe Application Error.”
“InfDefaultInstall.exe is not a valid Win32 application.”
“InfDefaultInstall.exe has encountered a problem and needs to close. We are sorry for the inconvenience.”
“Cannot find InfDefaultInstall.exe.”
“InfDefaultInstall.exe not found.”
“Error starting program: InfDefaultInstall.exe.”
“InfDefaultInstall.exe is not running.”
“InfDefaultInstall.exe failed.”
“Faulting Application Path: InfDefaultInstall.exe.”
— — — — — — — — — — — — — — — — — — — — — — — —
But this error is very different, my friend !!
screenshot from 2017-07-20 09-37-19
This means the merits of the subject!!
1:. Very fast consumption in memory
2:. Nuisance does not end While restarting the Widnows
-------------------------------- in Empire
screenshot from 2017-07-20 23-19-24

screenshot from 2017-07-20 23-19-58
Download Memory-spasm.ps1
https://github.com/jihadLkmaty218/Empire-v3.0/blob/master/Memory-spasm.ps1
upload file ps1 in path next 
Empire /data/module_source/management/
---------------------------
Download Memory-spasm.pyc
https://github.com/jihadLkmaty218/Empire-v3.0/blob/master/Memory-spasm.pyc
upload file Memory-spasm.pyc in path next 
/Empire/lib/modules/powershell/management
-------------
Download Memory-spasm.py
https://github.com/jihadLkmaty218/Empire-v3.0/blob/master/Memory-spasm.py
upload file :> Memory-spasm.pyc  in path next 
/Empire/lib/modules/powershell/management

### CODE REVIEW

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
Hi!
Your modifications are still not included in your PR, also,  you try to merge origin/master and origin/1.6.
[Tutorial](https://help.github.com/articles/creating-a-pull-request/)

:sunflower:

**Comment by jihadLkmaty218** [comment]
What is the right subject::)
websocket-test  On master

**Comment by ThePirateWhoSmellsOfSunflowers** [comment]
You need to fork the project (branch master), create a new branch, add your file, commit your modifications, push in your branch, pull request the project (on the dev branch).
You should learn how to use git before PR a project.  [Git is hard, but git is powerful](https://rogerdudler.github.io/git-guide/). 
:sunflower:

**Comment by rvrsh3ll** [comment]
http://imgur.com/VXSxAAE

Sorry.

**Pull request closed without merging**
