### PR TITLE
New module to monitor TCP connections

### PR DESCRIPTION
**Pull request by erikbarzdukas**
This module checks for TCP connections to a given domain name or IPv4 address at a user defined interval and alerts in the agent view if it detects a connection. My team needed to monitor a group of about 12 users that had access to sensitive data behind two factor web services, in order to then hijack their sessions. The basic powershell script came out of that. We were using it with Cobalt Strike as an aggressor script, but I prefer Empire and wanted to port the functionality. 

I developed based off the 2.0_beta branch, so I can switch the PR to the dev branch if that's preferred.

### CODE REVIEW

**Comment by killswitch-GUI** [comment]
Thanks for the pull! Any thought if you could also add in the Python version -- since this can be potentially useful on the OS X side? other than that I will talk with the team about this capability.

**Comment by erikbarzdukas** [comment]
Yes, I can definitely get a Python equivalent going. I'll get that going and push to the same branch when it's working.

**Comment by killswitch-GUI** [comment]
@erikbarzdukas thats great! for things like this, I can see value in having both supported!

**Comment by xorrior** [comment]
Tested this and it works. Thanks.

**Pull request merged**
