### PR TITLE
New::) Generate Script  .bashrc Module !! Payload Linux Empire ::)

### PR DESCRIPTION
**Pull request by jihadLkmaty218**
Now Let's Go In file Temp And the Next Transfer Script .bashrc from Temp To Home Or Root Yes ::)
It will then be implemented coding Payload On Terminal ! ::)
--------
============
screenshot from 2017-08-29 01-44-04
----------------------------------------
Download bashrc.py
https://github.com/jihadLkmaty218/Empire-v3.0/blob/master/bashrc.py
Path 
/Empire/lib/stagers/multi/
---------------------------
And bashrc.pyc
https://github.com/jihadLkmaty218/Empire-v3.0/blob/master/bashrc.pyc
Path 
/Empire/lib/stagers/multi/
---------------------------

### CODE REVIEW

**Comment by rvrsh3ll** [comment]
Your PR looks empty??

**Comment by jihadLkmaty218** [comment]
Now you have modified it On Github Download again bro Now  ::) :100: 
I want to get to know you more on Twitter my friend Normal Man :+1: 
screenshot from 2017-08-30 21-22-01

**Comment by jihadLkmaty218** [comment]
The video will show you every detail On Module ::)
https://www.youtube.com/watch?v=sycemsB5INc

**Comment by rvrsh3ll** [comment]
Looks cool but, your pull request is empty. Please try again.

**Pull request closed without merging**
