### PR TITLE
Add support for C# launcher

### PR DESCRIPTION
**Pull request by elitest**
This proposed PR generates a C# project that can be compiled in VS or SharpDevelop or whatever you choose.  It zips the source and outputs it to a specified directory.  In theory we could probably find a way to cross-compile, but shipping a zip of the source allows for customization if desired.  The solution targets .NET 2.0.

This is based off the work by @bneg and the article found here: https://bneg.io/2017/07/26/empire-without-powershell-exe/.

As always let me know if you have any questions or suggestions.

### CODE REVIEW

**Comment by bneg** [comment]
Check out SharpIre by 0xbadjuju

Jeremy Johnson, CISSP
C: 360.477.1614
________________________________

**Comment by xorrior** [comment]
@elitest Can you remove the portion that modifies the setup_database.py file? Thanks.

**Comment by elitest** [comment]
Thanks for the reminder @xorrior!  I swore I did that in a new branch!

**Comment by xorrior** [comment]
@elitest awesome, works perfectly. Thanks!

**Pull request merged**
