### PR TITLE
Facilitate some The things in infrastructure Empire

### PR DESCRIPTION
**Pull request by jihadLkmaty218**
this is Dev To Make infrastructure to Empire Flexible in some The things Like msfconsole Run empire Via Method invoke-empire
1 
screenshot from 2017-11-09 21-32-31
2 
screenshot from 2017-11-09 21-34-35
And Video //
https://www.youtube.com/watch?v=PulygmchOWs

### CODE REVIEW

**Comment by jihadLkmaty218** [comment]
@mattifestation @enigma0x3 Hello friends how do you see it in this/nice True /

**Comment by xorrior** [comment]
I look forward to your next PR!
https://media.giphy.com/media/26gZ1Ye2gkRUxtj9u/giphy.gif

**Comment by jihadLkmaty218** [comment]
So what is correct / dev With dev Or What ! Mr

**Comment by jihadLkmaty218** [comment]
Mr @xorrior Is there any concern in my work? 
The first time I made a ban to my Account in Twitter
I just wanted to get to know on you You rejected this  // Do not forget that only God is the conciliator in this work /
I give all my respect to you

**Comment by mattifestation** [comment]
@jihadLkmaty218 I'm not a maintainer of Empire, FYI. My feedback: you didn't actually submit anything in your PR other than a single line in the changelog. Next time, submit actual code for the Empire devs (of which I am not one) to review. I'm sure they would love to merge in some cool, future code once you actually submit some.

**Comment by jihadLkmaty218** [comment]
thank you Mr @mattifestation

**Pull request closed without merging**
