### PR TITLE
Fixed cookie name empty on agents and added function get_listener_cookies on helper

### PR DESCRIPTION
**Pull request by infosecn1nja**
@xorrior This PR is fixed cookie name empty on agents and added function get_listener_cookies on helpers to get active cookies on listeners.

### CODE REVIEW

**Comment by xorrior** [comment]
@infosecn1nja While testing this, it looks like there is an issue handling the routing packet when staging an agent spawned from psinject or shinject. Specifically when crafting the dispatcher message. On the dev branch there is no issue:

Dev Branch
image

PR
image

image

**Comment by infosecn1nja** [comment]
@xorrior On the dev branch there is no problem but of all cookie on the listeners is empty, if you see on the traffic. I've fixed this problem, can be checked again.

image

**Comment by xorrior** [comment]
@infosecn1nja Okay, I did some testing on this PR and everything seems to be working. Thanks!

**Comment by xorrior** [comment]
@infosecn1nja I'm going to revert this PR. Unfortunately, when starting an additional, non-http listener (http_com), The server does not identify the routing cookie and any agent requests are ignored.  

image

I suspect that your changes to the http listener will need to be apply to the other listeners as well.

**Comment by infosecn1nja** [comment]
@xorrior thanks for information, i will investigate it.

**Comment by infosecn1nja** [comment]
@xorrior Can you merge to dev again?

**Pull request merged**
