### PR TITLE
Add RWMCRS module

### PR DESCRIPTION
**Pull request by giMini**
The module is able to grab credentials from the Windows memory with a Microsoft signed debugger.

This module comes from PowerMemory suite.

### CODE REVIEW

**Comment by HarmJ0y** [comment]
Awesome, we will take a look at this and see about integrating it now that we've recovered from Vegas. @enigma0x3 - have you been able to take a look yet?

**Comment by enigma0x3** [comment]
Thanks @giMini,
I'm working through a few issues getting the module to work...debugging now.
Hope to have it worked out soon.

Thanks

**Comment by giMini** [comment]
Oh yeah :-)

**Comment by giMini** [comment]
Hi @enigma0x3,

Any news?

@giMini

**Pull request closed without merging**
