### PR TITLE
http_com Listener now evades Nessus plugin 99592

### PR DESCRIPTION
**Pull request by s0lst1c3**
Alright, good news. As promised, I've modified the http_com Listener to evade Nessus plugin 99592 using the same technique described in #890. As before, I've made sure the modified Listener is able to adequately evade the Nessus plugin. 

In the following screenshot, we perform a Nessus scan using plugin 99592 against a host running an unmodified Empire http_com Listener. The scan succeeds in detecting the Listener's presence.

screen shot 2018-02-01 at 1 50 15 am

Running the same scan against the enhanced http_com Listener reveals that Nessus is unable to detect the http_com Listener. 

screen shot 2018-02-01 at 1 52 59 am

Basic unit tests seem to be passing as well, as shown in the screenshot below.

screen shot 2018-02-01 at 2 42 25 am

### CODE REVIEW

**Comment by s0lst1c3** [comment]
Just took a look at the output from CircleCl. Looks like it's hanging on the part where the user is supposed to enter the server negotiation password:

```
Cloning into 'bomutils'...
remote: Counting objects: 246, done.
remote: Total 246 (delta 0), reused 0 (delta 0), pack-reused 246
Receiving objects: 100% (246/246), 1.20 MiB | 0 bytes/s, done.
Resolving deltas: 100% (126/126), done.
Checking connectivity... done.
g++ -o build/obj/mkbom.o -c -O2 -g0 -s -Wall  src/mkbom.cpp
g++ -o build/obj/printnode.o -c -O2 -g0 -s -Wall  src/printnode.cpp
g++ -o build/obj/crc32.o -c -O2 -g0 -s -Wall  src/crc32.cpp
g++ -o build/bin/mkbom  build/obj/mkbom.o build/obj/printnode.o build/obj/crc32.o 
g++ -o build/obj/dumpbom.o -c -O2 -g0 -s -Wall  src/dumpbom.cpp
g++ -o build/bin/dumpbom  build/obj/dumpbom.o build/obj/printnode.o build/obj/crc32.o 
g++ -o build/obj/lsbom.o -c -O2 -g0 -s -Wall  src/lsbom.cpp
g++ -o build/bin/lsbom  build/obj/lsbom.o build/obj/printnode.o build/obj/crc32.o 
g++ -o build/obj/ls4mkbom.o -c -O2 -g0 -s -Wall  src/ls4mkbom.cpp
g++ -o build/bin/ls4mkbom  build/obj/ls4mkbom.o build/obj/printnode.o build/obj/crc32.o 
gzip -c man/mkbom.1 > build/man/mkbom.1.gz
gzip -c man/dumpbom.1 > build/man/dumpbom.1.gz
gzip -c man/lsbom.1 > build/man/lsbom.1.gz
gzip -c man/ls4mkbom.1 > build/man/ls4mkbom.1.gz
install -d /usr/bin
install -d /usr/share/man/man1
install -m 0755 build/bin/mkbom build/bin/dumpbom build/bin/lsbom build/bin/ls4mkbom /usr/bin
install -m 0644 build/man/mkbom.1.gz build/man/dumpbom.1.gz build/man/lsbom.1.gz build/man/ls4mkbom.1.gz /usr/share/man/man1
install -d /usr/bin
install -d /usr/share/man/man1
install -m 0755 build/bin/mkbom build/bin/dumpbom build/bin/lsbom build/bin/ls4mkbom /usr/bin
install -m 0644 build/man/mkbom.1.gz build/man/dumpbom.1.gz build/man/lsbom.1.gz build/man/ls4mkbom.1.gz /usr/share/man/man1

 [>] Enter server negotiation password, enter for random generation: Too long with no output (exceeded 10m0s)
```

**Comment by xorrior** [comment]
Ignore CircleCI @s0lst1c3. It's going away soon.

**Comment by s0lst1c3** [comment]
Haha, fair enough. Farewell CircleCl!

**Comment by xorrior** [comment]
@s0lst1c3 Tested your changes and didn't run into any issues. Thanks again @s0lst1c3 !

**Comment by s0lst1c3** [comment]
Anytime man!

**Pull request merged**
