### PR TITLE
Added a module for SOCKSv5 proxying

### PR DESCRIPTION
**Pull request by klustic**
When executed, this module connects back to a designated AlmondRocks server under SSL. The AlmondRocks server acts as a SOCKSv5 proxy, and multiplexes all SOCKS communications over the single SSL connection to/through the target, enabling any SOCKSv5 client (e.g. curl, proxychains) to extend past NAT devices into the target network.

This is based on the following work:
https://github.com/klustic/AlmondRocks

** Server Usage **
$ ./almondrocks.py server -d -t 8443 --cert cert.pem --key key.pem

** Empire Usage **
set HOST 192.168.20.10
set PORT 8443
set Agent ...

### CODE REVIEW

**Comment by xorrior** [comment]
Will test this once I have a macOS test box. Thanks for the PR.

**Comment by klustic** [comment]
Awesome, thanks! I have tested on Ubuntu 14 / 16 LTS and CentOS 7. Windows will likely fail due to use of select() on stdin and the decision to use Unix sockets. I don't see a reason why OS X should have issues. Keep me posted on your findings

**Comment by xorrior** [comment]
Didn't get the chance to test on OSX but it looks good. Tested on Ubuntu 16 and it worked like charm. Thanks again.

**Comment by xorrior** [comment]
fyi, I'm going to move the module after merging to the management folder.

**Comment by klustic** [comment]
Sweet! Thanks, I've used it a bunch, I hope it will come in handy for others.

**Comment by johncole2017** [comment]
Hi,
Please explain how can we use this? I mean how can i use SOCKS proxy for http listeners with windows/hta stage generated ?
thanks

**Comment by klustic** [comment]
Hi @johncole2017 ,

To use this module, you need [the AlmondRocks server](https://github.com/klustic/AlmondRocks)

Clone that project, generate TLS certs, and start the server (instructions on that github's readme). Then `interact` with your agent, and:
```
usemodule management/multi/socks
set HOST <your AlmondRocks server>
set PORT <your AlmondRocks port>
execute
```

You should get a connection on your AlmondRocks server from your agent. You also notice that port 1080 is listening on your AlmondRocks server loopback. This is a SOCKS proxy, so you can point proxychains or some SOCKSv5 proxy-aware app at it and that traffic will proxy through your Empire agent.

Hope this helps

**Pull request merged**
