### PR TITLE
Update Invoke-Mimikatz

### PR DESCRIPTION
**Pull request by phra**
see #1293 

```
  .#####.   mimikatz 2.1.1 (x64) #17763 Dec 31 2018 01:15:11
 .## ^ ##.  "A La Vie, A L'Amour" - (oe.eo) ** Kitten Edition **
 ## / \ ##  /*** Benjamin DELPY `gentilkiwi` ( benjamin@gentilkiwi.com )
 ## \ / ##       > http://blog.gentilkiwi.com/mimikatz
 '## v ##'       Vincent LE TOUX             ( vincent.letoux@gmail.com )
  '#####'        > http://pingcastle.com / http://mysmartlogon.com   ***/
```

### CODE REVIEW

**Comment by phra** [comment]
supersede #1194

**Comment by mr64bit** [comment]
Hi Phra, thanks for the PR. I updated Invoke-Mimikatz in `dev`. Your pull had a bunch of unnecessary formatting changes, so I patched the base64 bytes myself.

**Comment by phra** [comment]
@mr64bit do you have also updated the `GetProcAddr` invocation? i can't see the diff from github.

**Comment by mr64bit** [comment]
That was done many months ago, but it’s still in the dev branch.

**Pull request closed without merging**
