### PR TITLE
show current UAC level

### PR DESCRIPTION
**Pull request by winnie22**
simple module that enumerate current UAC level

### CODE REVIEW

**Comment by killswitch-GUI** [comment]
awesome work :) will test and push to dev!

**Comment by rvrsh3ll** [comment]
Thanks for the module! Currently getting an error during testing:

[!] Exception: generate() takes exactly 1 argument (3 given)

**Comment by rvrsh3ll** [comment]
So, now that we have "Obfuscated empire". The generate(self) needs to look like this generate(self, obfuscate=False, obfuscationCommand="")

Please fix

**Comment by winnie22** [comment]
Hi, fixed in this PR and similary in PR #596. Thanks

**Comment by xorrior** [comment]
Tested and confirmed working. @winnie22  thanks!

**Pull request merged**
